# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: frcnn.yaml # choose the datamodule for evaluation
  - model: frcnn.yaml
  - callbacks: default
  - logger: tensorboard.yaml
  - trainer: default.yaml
  - log_dir: evaluation.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data

print_config: True

ignore_warnings: True

seed: null

name: "default"

# passing checkpoint path is necessary
# ckpt_path: ${original_work_dir}/scripts/pretrained_model/2023-04-25_12-42-09/checkpoints/epoch_029.ckpt
ckpt_path: 
