Starting script
The activation script must be sourced, otherwise the virtual environment will not work.
Setting vars
[[36m2023-04-25 12:42:43,354[0m][[34mtorch.distributed.nn.jit.instantiator[0m][[32mINFO[0m] - Created a temporary directory at /tmp/tmpar0usvsx[0m
[[36m2023-04-25 12:42:43,354[0m][[34mtorch.distributed.nn.jit.instantiator[0m][[32mINFO[0m] - Writing /tmp/tmpar0usvsx/_remote_module_non_scriptable.py[0m
[[36m2023-04-25 12:42:44,238[0m][[34mobject_detection.utils[0m][[32mINFO[0m] - Disabling python warnings! <config.ignore_warnings=True>[0m
[[36m2023-04-25 12:42:44,238[0m][[34mobject_detection.utils[0m][[32mINFO[0m] - Printing config tree with Rich! <config.print_config=True>[0m
CONFIG
├── datamodule
│   └── _target_: object_detection.datamodules.frcnn_datamodule.frcnn_datamodule                                                                                                                         
│       train_data_dir: /p/project/hai_hmgu/workspace/harsha/OrgaQuantData/train                                                                                                                         
│       test_data_dir: /p/project/hai_hmgu/workspace/harsha/OrgaQuantData/test                                                                                                                           
│       train_labels_file: /p/project/hai_hmgu/workspace/harsha/OrgaQuantData/train_labels.csv                                                                                                           
│       test_labels_file: /p/project/hai_hmgu/workspace/harsha/OrgaQuantData/test_labels.csv                                                                                                             
│       batch_size: 16                                                                                                                                                                                   
│       num_workers: 0                                                                                                                                                                                   
│       pin_memory: false                                                                                                                                                                                
│       aug_flag: 'N'                                                                                                                                                                                    
│                                                                                                                                                                                                        
├── model
│   └── _target_: object_detection.models.frcnn_module.frcnn_module                                                                                                                                      
│       lr: 0.001                                                                                                                                                                                        
│       weight_decay: 0.0005                                                                                                                                                                             
│       momentum: 0.9                                                                                                                                                                                    
│       nms_thresh: 0.2                                                                                                                                                                                  
│       iou_thresh: 0.7                                                                                                                                                                                  
│       net:                                                                                                                                                                                             
│         _target_: object_detection.models.components.frcnn.frcnn                                                                                                                                       
│         num_classes: 2                                                                                                                                                                                 
│                                                                                                                                                                                                        
├── callbacks
│   └── model_checkpoint:                                                                                                                                                                                
│         _target_: pytorch_lightning.callbacks.ModelCheckpoint                                                                                                                                          
│         monitor: validation/loss                                                                                                                                                                       
│         mode: min                                                                                                                                                                                      
│         save_top_k: -1                                                                                                                                                                                 
│         every_n_epochs: 5                                                                                                                                                                              
│         save_last: true                                                                                                                                                                                
│         verbose: false                                                                                                                                                                                 
│         dirpath: checkpoints/                                                                                                                                                                          
│         filename: epoch_{epoch:03d}                                                                                                                                                                    
│         auto_insert_metric_name: false                                                                                                                                                                 
│       early_stopping:                                                                                                                                                                                  
│         _target_: pytorch_lightning.callbacks.EarlyStopping                                                                                                                                            
│         monitor: validation/loss                                                                                                                                                                       
│         mode: min                                                                                                                                                                                      
│         patience: 10                                                                                                                                                                                   
│         min_delta: 0                                                                                                                                                                                   
│       model_summary:                                                                                                                                                                                   
│         _target_: pytorch_lightning.callbacks.RichModelSummary                                                                                                                                         
│         max_depth: -1                                                                                                                                                                                  
│       rich_progress_bar:                                                                                                                                                                               
│         _target_: pytorch_lightning.callbacks.RichProgressBar                                                                                                                                          
│                                                                                                                                                                                                        
├── logger
│   └── tensorboard:                                                                                                                                                                                     
│         _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger                                                                                                                              
│         save_dir: /p/project/hai_hmgu/workspace/harsha/ObjectDetection/scripts/logs/tensorboard                                                                                                        
│         name: null                                                                                                                                                                                     
│         version: default                                                                                                                                                                               
│         log_graph: false                                                                                                                                                                               
│         default_hp_metric: true                                                                                                                                                                        
│         prefix: ''                                                                                                                                                                                     
│                                                                                                                                                                                                        
├── trainer
│   └── _target_: pytorch_lightning.Trainer                                                                                                                                                              
│       accelerator: gpu                                                                                                                                                                                 
│       devices: 4                                                                                                                                                                                       
│       min_epochs: 25                                                                                                                                                                                   
│       max_epochs: 30                                                                                                                                                                                   
│       num_sanity_val_steps: 1                                                                                                                                                                          
│       check_val_every_n_epoch: 1                                                                                                                                                                       
│       val_check_interval: 1.0                                                                                                                                                                          
│                                                                                                                                                                                                        
├── original_work_dir
│   └── /p/project/hai_hmgu/workspace/harsha/ObjectDetection/scripts                                                                                                                                     
├── data_dir
│   └── /p/project/hai_hmgu/workspace/harsha/OrgaQuantData                                                                                                                                               
├── print_config
│   └── True                                                                                                                                                                                             
├── ignore_warnings
│   └── True                                                                                                                                                                                             
├── train
│   └── True                                                                                                                                                                                             
├── test
│   └── True                                                                                                                                                                                             
├── seed
│   └── None                                                                                                                                                                                             
└── name
    └── default                                                                                                                                                                                          
[[36m2023-04-25 12:42:44,296[0m][[34mobject_detection.training_pipeline[0m][[32mINFO[0m] - Instantiating datamodule <object_detection.datamodules.frcnn_datamodule.frcnn_datamodule>[0m
[[36m2023-04-25 12:42:55,318[0m][[34mobject_detection.training_pipeline[0m][[32mINFO[0m] - Instantiating model <object_detection.models.frcnn_module.frcnn_module>[0m
[[36m2023-04-25 12:42:56,145[0m][[34mobject_detection.training_pipeline[0m][[32mINFO[0m] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>[0m
[[36m2023-04-25 12:42:56,147[0m][[34mobject_detection.training_pipeline[0m][[32mINFO[0m] - Instantiating callback <pytorch_lightning.callbacks.EarlyStopping>[0m
[[36m2023-04-25 12:42:56,148[0m][[34mobject_detection.training_pipeline[0m][[32mINFO[0m] - Instantiating callback <pytorch_lightning.callbacks.RichModelSummary>[0m
[[36m2023-04-25 12:42:56,148[0m][[34mobject_detection.training_pipeline[0m][[32mINFO[0m] - Instantiating callback <pytorch_lightning.callbacks.RichProgressBar>[0m
[[36m2023-04-25 12:42:56,149[0m][[34mobject_detection.training_pipeline[0m][[32mINFO[0m] - Instantiating logger <pytorch_lightning.loggers.tensorboard.TensorBoardLogger>[0m
[[36m2023-04-25 12:42:56,152[0m][[34mobject_detection.training_pipeline[0m][[32mINFO[0m] - Instantiating trainer <pytorch_lightning.Trainer>[0m
[[36m2023-04-25 12:42:56,297[0m][[34mpytorch_lightning.utilities.rank_zero[0m][[32mINFO[0m] - Trainer already configured with model summary callbacks: [<class 'pytorch_lightning.callbacks.rich_model_summary.RichModelSummary'>]. Skipping setting a default `ModelSummary` callback.[0m
[[36m2023-04-25 12:42:56,314[0m][[34mpytorch_lightning.utilities.rank_zero[0m][[32mINFO[0m] - GPU available: True (cuda), used: True[0m
[[36m2023-04-25 12:42:56,314[0m][[34mpytorch_lightning.utilities.rank_zero[0m][[32mINFO[0m] - TPU available: False, using: 0 TPU cores[0m
[[36m2023-04-25 12:42:56,314[0m][[34mpytorch_lightning.utilities.rank_zero[0m][[32mINFO[0m] - IPU available: False, using: 0 IPUs[0m
[[36m2023-04-25 12:42:56,314[0m][[34mpytorch_lightning.utilities.rank_zero[0m][[32mINFO[0m] - HPU available: False, using: 0 HPUs[0m
[[36m2023-04-25 12:42:56,314[0m][[34mpytorch_lightning.utilities.rank_zero[0m][[32mINFO[0m] - `Trainer(val_check_interval=1.0)` was configured so validation will run at the end of the training epoch..[0m
[[36m2023-04-25 12:42:56,314[0m][[34mobject_detection.training_pipeline[0m][[32mINFO[0m] - Logging hyperparameters![0m
[[36m2023-04-25 12:43:00,222[0m][[34mobject_detection.training_pipeline[0m][[32mINFO[0m] - Starting training![0m
[[36m2023-04-25 12:43:00,408[0m][[34mlightning_fabric.utilities.distributed[0m][[32mINFO[0m] - Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/4[0m
[[36m2023-04-25 12:43:03,605[0m][[34mtorch.distributed.nn.jit.instantiator[0m][[32mINFO[0m] - Created a temporary directory at /tmp/tmpz838g84i[0m
[[36m2023-04-25 12:43:03,605[0m][[34mtorch.distributed.nn.jit.instantiator[0m][[32mINFO[0m] - Writing /tmp/tmpz838g84i/_remote_module_non_scriptable.py[0m
[[36m2023-04-25 12:43:03,637[0m][[34mtorch.distributed.nn.jit.instantiator[0m][[32mINFO[0m] - Created a temporary directory at /tmp/tmpsm3o4rrw[0m
[[36m2023-04-25 12:43:03,637[0m][[34mtorch.distributed.nn.jit.instantiator[0m][[32mINFO[0m] - Writing /tmp/tmpsm3o4rrw/_remote_module_non_scriptable.py[0m
[[36m2023-04-25 12:43:03,670[0m][[34mtorch.distributed.nn.jit.instantiator[0m][[32mINFO[0m] - Created a temporary directory at /tmp/tmpkw6qte6s[0m
[[36m2023-04-25 12:43:03,670[0m][[34mtorch.distributed.nn.jit.instantiator[0m][[32mINFO[0m] - Writing /tmp/tmpkw6qte6s/_remote_module_non_scriptable.py[0m
[[36m2023-04-25 12:43:06,627[0m][[34mlightning_fabric.utilities.distributed[0m][[32mINFO[0m] - Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/4[0m
[[36m2023-04-25 12:43:06,696[0m][[34mlightning_fabric.utilities.distributed[0m][[32mINFO[0m] - Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/4[0m
[[36m2023-04-25 12:43:06,745[0m][[34mlightning_fabric.utilities.distributed[0m][[32mINFO[0m] - Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/4[0m
[[36m2023-04-25 12:43:07,562[0m][[34mtorch.distributed.distributed_c10d[0m][[32mINFO[0m] - Added key: store_based_barrier_key:1 to store for rank: 1[0m
[[36m2023-04-25 12:43:07,571[0m][[34mtorch.distributed.distributed_c10d[0m][[32mINFO[0m] - Added key: store_based_barrier_key:1 to store for rank: 0[0m
[[36m2023-04-25 12:43:07,572[0m][[34mtorch.distributed.distributed_c10d[0m][[32mINFO[0m] - Added key: store_based_barrier_key:1 to store for rank: 3[0m
[[36m2023-04-25 12:43:07,575[0m][[34mtorch.distributed.distributed_c10d[0m][[32mINFO[0m] - Added key: store_based_barrier_key:1 to store for rank: 2[0m
[[36m2023-04-25 12:43:07,575[0m][[34mtorch.distributed.distributed_c10d[0m][[32mINFO[0m] - Rank 2: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.[0m
[[36m2023-04-25 12:43:07,582[0m][[34mtorch.distributed.distributed_c10d[0m][[32mINFO[0m] - Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.[0m
[[36m2023-04-25 12:43:07,582[0m][[34mpytorch_lightning.utilities.rank_zero[0m][[32mINFO[0m] - ----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 4 processes
----------------------------------------------------------------------------------------------------
[0m
[[36m2023-04-25 12:43:07,582[0m][[34mtorch.distributed.distributed_c10d[0m][[32mINFO[0m] - Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.[0m
[[36m2023-04-25 12:43:07,583[0m][[34mtorch.distributed.distributed_c10d[0m][[32mINFO[0m] - Rank 3: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.[0m
[[36m2023-04-25 12:43:07,616[0m][[34mpytorch_lightning.utilities.rank_zero[0m][[32mINFO[0m] - You are using a CUDA device ('NVIDIA A100-SXM4-40GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision[0m
Number of training images and test images
1629 112
Dimension of the image torch.Size([3, 300, 300])
[[36m2023-04-25 12:43:11,674[0m][[34mpytorch_lightning.accelerators.cuda[0m][[32mINFO[0m] - LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3     ][0m
Number of training images and test images
1629 112
Dimension of the image torch.Size([3, 300, 300])
[[36m2023-04-25 12:43:11,675[0m][[34mpytorch_lightning.accelerators.cuda[0m][[32mINFO[0m] - LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,2,3     ][0m
Number of training images and test images
1629 112
Dimension of the image torch.Size([3, 300, 300])
[[36m2023-04-25 12:43:11,675[0m][[34mpytorch_lightning.accelerators.cuda[0m][[32mINFO[0m] - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3     ][0m
Number of training images and test images
1629 112
Dimension of the image torch.Size([3, 300, 300])
[[36m2023-04-25 12:43:11,675[0m][[34mpytorch_lightning.accelerators.cuda[0m][[32mINFO[0m] - LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,2,3     ][0m
┏━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓
┃     ┃ Name                                          ┃ Type                     ┃ Params ┃
┡━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩
│ 0   │ net                                           │ frcnn                    │ 41.3 M │
│ 1   │ net.model                                     │ FasterRCNN               │ 41.3 M │
│ 2   │ net.model.transform                           │ GeneralizedRCNNTransform │      0 │
│ 3   │ net.model.backbone                            │ BackboneWithFPN          │ 26.8 M │
│ 4   │ net.model.backbone.body                       │ IntermediateLayerGetter  │ 23.5 M │
│ 5   │ net.model.backbone.body.conv1                 │ Conv2d                   │  9.4 K │
│ 6   │ net.model.backbone.body.bn1                   │ FrozenBatchNorm2d        │      0 │
│ 7   │ net.model.backbone.body.relu                  │ ReLU                     │      0 │
│ 8   │ net.model.backbone.body.maxpool               │ MaxPool2d                │      0 │
│ 9   │ net.model.backbone.body.layer1                │ Sequential               │  212 K │
│ 10  │ net.model.backbone.body.layer1.0              │ Bottleneck               │ 73.7 K │
│ 11  │ net.model.backbone.body.layer1.0.conv1        │ Conv2d                   │  4.1 K │
│ 12  │ net.model.backbone.body.layer1.0.bn1          │ FrozenBatchNorm2d        │      0 │
│ 13  │ net.model.backbone.body.layer1.0.conv2        │ Conv2d                   │ 36.9 K │
│ 14  │ net.model.backbone.body.layer1.0.bn2          │ FrozenBatchNorm2d        │      0 │
│ 15  │ net.model.backbone.body.layer1.0.conv3        │ Conv2d                   │ 16.4 K │
│ 16  │ net.model.backbone.body.layer1.0.bn3          │ FrozenBatchNorm2d        │      0 │
│ 17  │ net.model.backbone.body.layer1.0.relu         │ ReLU                     │      0 │
│ 18  │ net.model.backbone.body.layer1.0.downsample   │ Sequential               │ 16.4 K │
│ 19  │ net.model.backbone.body.layer1.0.downsample.0 │ Conv2d                   │ 16.4 K │
│ 20  │ net.model.backbone.body.layer1.0.downsample.1 │ FrozenBatchNorm2d        │      0 │
│ 21  │ net.model.backbone.body.layer1.1              │ Bottleneck               │ 69.6 K │
│ 22  │ net.model.backbone.body.layer1.1.conv1        │ Conv2d                   │ 16.4 K │
│ 23  │ net.model.backbone.body.layer1.1.bn1          │ FrozenBatchNorm2d        │      0 │
│ 24  │ net.model.backbone.body.layer1.1.conv2        │ Conv2d                   │ 36.9 K │
│ 25  │ net.model.backbone.body.layer1.1.bn2          │ FrozenBatchNorm2d        │      0 │
│ 26  │ net.model.backbone.body.layer1.1.conv3        │ Conv2d                   │ 16.4 K │
│ 27  │ net.model.backbone.body.layer1.1.bn3          │ FrozenBatchNorm2d        │      0 │
│ 28  │ net.model.backbone.body.layer1.1.relu         │ ReLU                     │      0 │
│ 29  │ net.model.backbone.body.layer1.2              │ Bottleneck               │ 69.6 K │
│ 30  │ net.model.backbone.body.layer1.2.conv1        │ Conv2d                   │ 16.4 K │
│ 31  │ net.model.backbone.body.layer1.2.bn1          │ FrozenBatchNorm2d        │      0 │
│ 32  │ net.model.backbone.body.layer1.2.conv2        │ Conv2d                   │ 36.9 K │
│ 33  │ net.model.backbone.body.layer1.2.bn2          │ FrozenBatchNorm2d        │      0 │
│ 34  │ net.model.backbone.body.layer1.2.conv3        │ Conv2d                   │ 16.4 K │
│ 35  │ net.model.backbone.body.layer1.2.bn3          │ FrozenBatchNorm2d        │      0 │
│ 36  │ net.model.backbone.body.layer1.2.relu         │ ReLU                     │      0 │
│ 37  │ net.model.backbone.body.layer2                │ Sequential               │  1.2 M │
│ 38  │ net.model.backbone.body.layer2.0              │ Bottleneck               │  376 K │
│ 39  │ net.model.backbone.body.layer2.0.conv1        │ Conv2d                   │ 32.8 K │
│ 40  │ net.model.backbone.body.layer2.0.bn1          │ FrozenBatchNorm2d        │      0 │
│ 41  │ net.model.backbone.body.layer2.0.conv2        │ Conv2d                   │  147 K │
│ 42  │ net.model.backbone.body.layer2.0.bn2          │ FrozenBatchNorm2d        │      0 │
│ 43  │ net.model.backbone.body.layer2.0.conv3        │ Conv2d                   │ 65.5 K │
│ 44  │ net.model.backbone.body.layer2.0.bn3          │ FrozenBatchNorm2d        │      0 │
│ 45  │ net.model.backbone.body.layer2.0.relu         │ ReLU                     │      0 │
│ 46  │ net.model.backbone.body.layer2.0.downsample   │ Sequential               │  131 K │
│ 47  │ net.model.backbone.body.layer2.0.downsample.0 │ Conv2d                   │  131 K │
│ 48  │ net.model.backbone.body.layer2.0.downsample.1 │ FrozenBatchNorm2d        │      0 │
│ 49  │ net.model.backbone.body.layer2.1              │ Bottleneck               │  278 K │
│ 50  │ net.model.backbone.body.layer2.1.conv1        │ Conv2d                   │ 65.5 K │
│ 51  │ net.model.backbone.body.layer2.1.bn1          │ FrozenBatchNorm2d        │      0 │
│ 52  │ net.model.backbone.body.layer2.1.conv2        │ Conv2d                   │  147 K │
│ 53  │ net.model.backbone.body.layer2.1.bn2          │ FrozenBatchNorm2d        │      0 │
│ 54  │ net.model.backbone.body.layer2.1.conv3        │ Conv2d                   │ 65.5 K │
│ 55  │ net.model.backbone.body.layer2.1.bn3          │ FrozenBatchNorm2d        │      0 │
│ 56  │ net.model.backbone.body.layer2.1.relu         │ ReLU                     │      0 │
│ 57  │ net.model.backbone.body.layer2.2              │ Bottleneck               │  278 K │
│ 58  │ net.model.backbone.body.layer2.2.conv1        │ Conv2d                   │ 65.5 K │
│ 59  │ net.model.backbone.body.layer2.2.bn1          │ FrozenBatchNorm2d        │      0 │
│ 60  │ net.model.backbone.body.layer2.2.conv2        │ Conv2d                   │  147 K │
│ 61  │ net.model.backbone.body.layer2.2.bn2          │ FrozenBatchNorm2d        │      0 │
│ 62  │ net.model.backbone.body.layer2.2.conv3        │ Conv2d                   │ 65.5 K │
│ 63  │ net.model.backbone.body.layer2.2.bn3          │ FrozenBatchNorm2d        │      0 │
│ 64  │ net.model.backbone.body.layer2.2.relu         │ ReLU                     │      0 │
│ 65  │ net.model.backbone.body.layer2.3              │ Bottleneck               │  278 K │
│ 66  │ net.model.backbone.body.layer2.3.conv1        │ Conv2d                   │ 65.5 K │
│ 67  │ net.model.backbone.body.layer2.3.bn1          │ FrozenBatchNorm2d        │      0 │
│ 68  │ net.model.backbone.body.layer2.3.conv2        │ Conv2d                   │  147 K │
│ 69  │ net.model.backbone.body.layer2.3.bn2          │ FrozenBatchNorm2d        │      0 │
│ 70  │ net.model.backbone.body.layer2.3.conv3        │ Conv2d                   │ 65.5 K │
│ 71  │ net.model.backbone.body.layer2.3.bn3          │ FrozenBatchNorm2d        │      0 │
│ 72  │ net.model.backbone.body.layer2.3.relu         │ ReLU                     │      0 │
│ 73  │ net.model.backbone.body.layer3                │ Sequential               │  7.1 M │
│ 74  │ net.model.backbone.body.layer3.0              │ Bottleneck               │  1.5 M │
│ 75  │ net.model.backbone.body.layer3.0.conv1        │ Conv2d                   │  131 K │
│ 76  │ net.model.backbone.body.layer3.0.bn1          │ FrozenBatchNorm2d        │      0 │
│ 77  │ net.model.backbone.body.layer3.0.conv2        │ Conv2d                   │  589 K │
│ 78  │ net.model.backbone.body.layer3.0.bn2          │ FrozenBatchNorm2d        │      0 │
│ 79  │ net.model.backbone.body.layer3.0.conv3        │ Conv2d                   │  262 K │
│ 80  │ net.model.backbone.body.layer3.0.bn3          │ FrozenBatchNorm2d        │      0 │
│ 81  │ net.model.backbone.body.layer3.0.relu         │ ReLU                     │      0 │
│ 82  │ net.model.backbone.body.layer3.0.downsample   │ Sequential               │  524 K │
│ 83  │ net.model.backbone.body.layer3.0.downsample.0 │ Conv2d                   │  524 K │
│ 84  │ net.model.backbone.body.layer3.0.downsample.1 │ FrozenBatchNorm2d        │      0 │
│ 85  │ net.model.backbone.body.layer3.1              │ Bottleneck               │  1.1 M │
│ 86  │ net.model.backbone.body.layer3.1.conv1        │ Conv2d                   │  262 K │
│ 87  │ net.model.backbone.body.layer3.1.bn1          │ FrozenBatchNorm2d        │      0 │
│ 88  │ net.model.backbone.body.layer3.1.conv2        │ Conv2d                   │  589 K │
│ 89  │ net.model.backbone.body.layer3.1.bn2          │ FrozenBatchNorm2d        │      0 │
│ 90  │ net.model.backbone.body.layer3.1.conv3        │ Conv2d                   │  262 K │
│ 91  │ net.model.backbone.body.layer3.1.bn3          │ FrozenBatchNorm2d        │      0 │
│ 92  │ net.model.backbone.body.layer3.1.relu         │ ReLU                     │      0 │
│ 93  │ net.model.backbone.body.layer3.2              │ Bottleneck               │  1.1 M │
│ 94  │ net.model.backbone.body.layer3.2.conv1        │ Conv2d                   │  262 K │
│ 95  │ net.model.backbone.body.layer3.2.bn1          │ FrozenBatchNorm2d        │      0 │
│ 96  │ net.model.backbone.body.layer3.2.conv2        │ Conv2d                   │  589 K │
│ 97  │ net.model.backbone.body.layer3.2.bn2          │ FrozenBatchNorm2d        │      0 │
│ 98  │ net.model.backbone.body.layer3.2.conv3        │ Conv2d                   │  262 K │
│ 99  │ net.model.backbone.body.layer3.2.bn3          │ FrozenBatchNorm2d        │      0 │
│ 100 │ net.model.backbone.body.layer3.2.relu         │ ReLU                     │      0 │
│ 101 │ net.model.backbone.body.layer3.3              │ Bottleneck               │  1.1 M │
│ 102 │ net.model.backbone.body.layer3.3.conv1        │ Conv2d                   │  262 K │
│ 103 │ net.model.backbone.body.layer3.3.bn1          │ FrozenBatchNorm2d        │      0 │
│ 104 │ net.model.backbone.body.layer3.3.conv2        │ Conv2d                   │  589 K │
│ 105 │ net.model.backbone.body.layer3.3.bn2          │ FrozenBatchNorm2d        │      0 │
│ 106 │ net.model.backbone.body.layer3.3.conv3        │ Conv2d                   │  262 K │
│ 107 │ net.model.backbone.body.layer3.3.bn3          │ FrozenBatchNorm2d        │      0 │
│ 108 │ net.model.backbone.body.layer3.3.relu         │ ReLU                     │      0 │
│ 109 │ net.model.backbone.body.layer3.4              │ Bottleneck               │  1.1 M │
│ 110 │ net.model.backbone.body.layer3.4.conv1        │ Conv2d                   │  262 K │
│ 111 │ net.model.backbone.body.layer3.4.bn1          │ FrozenBatchNorm2d        │      0 │
│ 112 │ net.model.backbone.body.layer3.4.conv2        │ Conv2d                   │  589 K │
│ 113 │ net.model.backbone.body.layer3.4.bn2          │ FrozenBatchNorm2d        │      0 │
│ 114 │ net.model.backbone.body.layer3.4.conv3        │ Conv2d                   │  262 K │
│ 115 │ net.model.backbone.body.layer3.4.bn3          │ FrozenBatchNorm2d        │      0 │
│ 116 │ net.model.backbone.body.layer3.4.relu         │ ReLU                     │      0 │
│ 117 │ net.model.backbone.body.layer3.5              │ Bottleneck               │  1.1 M │
│ 118 │ net.model.backbone.body.layer3.5.conv1        │ Conv2d                   │  262 K │
│ 119 │ net.model.backbone.body.layer3.5.bn1          │ FrozenBatchNorm2d        │      0 │
│ 120 │ net.model.backbone.body.layer3.5.conv2        │ Conv2d                   │  589 K │
│ 121 │ net.model.backbone.body.layer3.5.bn2          │ FrozenBatchNorm2d        │      0 │
│ 122 │ net.model.backbone.body.layer3.5.conv3        │ Conv2d                   │  262 K │
│ 123 │ net.model.backbone.body.layer3.5.bn3          │ FrozenBatchNorm2d        │      0 │
│ 124 │ net.model.backbone.body.layer3.5.relu         │ ReLU                     │      0 │
│ 125 │ net.model.backbone.body.layer4                │ Sequential               │ 14.9 M │
│ 126 │ net.model.backbone.body.layer4.0              │ Bottleneck               │  6.0 M │
│ 127 │ net.model.backbone.body.layer4.0.conv1        │ Conv2d                   │  524 K │
│ 128 │ net.model.backbone.body.layer4.0.bn1          │ FrozenBatchNorm2d        │      0 │
│ 129 │ net.model.backbone.body.layer4.0.conv2        │ Conv2d                   │  2.4 M │
│ 130 │ net.model.backbone.body.layer4.0.bn2          │ FrozenBatchNorm2d        │      0 │
│ 131 │ net.model.backbone.body.layer4.0.conv3        │ Conv2d                   │  1.0 M │
│ 132 │ net.model.backbone.body.layer4.0.bn3          │ FrozenBatchNorm2d        │      0 │
│ 133 │ net.model.backbone.body.layer4.0.relu         │ ReLU                     │      0 │
│ 134 │ net.model.backbone.body.layer4.0.downsample   │ Sequential               │  2.1 M │
│ 135 │ net.model.backbone.body.layer4.0.downsample.0 │ Conv2d                   │  2.1 M │
│ 136 │ net.model.backbone.body.layer4.0.downsample.1 │ FrozenBatchNorm2d        │      0 │
│ 137 │ net.model.backbone.body.layer4.1              │ Bottleneck               │  4.5 M │
│ 138 │ net.model.backbone.body.layer4.1.conv1        │ Conv2d                   │  1.0 M │
│ 139 │ net.model.backbone.body.layer4.1.bn1          │ FrozenBatchNorm2d        │      0 │
│ 140 │ net.model.backbone.body.layer4.1.conv2        │ Conv2d                   │  2.4 M │
│ 141 │ net.model.backbone.body.layer4.1.bn2          │ FrozenBatchNorm2d        │      0 │
│ 142 │ net.model.backbone.body.layer4.1.conv3        │ Conv2d                   │  1.0 M │
│ 143 │ net.model.backbone.body.layer4.1.bn3          │ FrozenBatchNorm2d        │      0 │
│ 144 │ net.model.backbone.body.layer4.1.relu         │ ReLU                     │      0 │
│ 145 │ net.model.backbone.body.layer4.2              │ Bottleneck               │  4.5 M │
│ 146 │ net.model.backbone.body.layer4.2.conv1        │ Conv2d                   │  1.0 M │
│ 147 │ net.model.backbone.body.layer4.2.bn1          │ FrozenBatchNorm2d        │      0 │
│ 148 │ net.model.backbone.body.layer4.2.conv2        │ Conv2d                   │  2.4 M │
│ 149 │ net.model.backbone.body.layer4.2.bn2          │ FrozenBatchNorm2d        │      0 │
│ 150 │ net.model.backbone.body.layer4.2.conv3        │ Conv2d                   │  1.0 M │
│ 151 │ net.model.backbone.body.layer4.2.bn3          │ FrozenBatchNorm2d        │      0 │
│ 152 │ net.model.backbone.body.layer4.2.relu         │ ReLU                     │      0 │
│ 153 │ net.model.backbone.fpn                        │ FeaturePyramidNetwork    │  3.3 M │
│ 154 │ net.model.backbone.fpn.inner_blocks           │ ModuleList               │  984 K │
│ 155 │ net.model.backbone.fpn.inner_blocks.0         │ Conv2dNormActivation     │ 65.8 K │
│ 156 │ net.model.backbone.fpn.inner_blocks.0.0       │ Conv2d                   │ 65.8 K │
│ 157 │ net.model.backbone.fpn.inner_blocks.1         │ Conv2dNormActivation     │  131 K │
│ 158 │ net.model.backbone.fpn.inner_blocks.1.0       │ Conv2d                   │  131 K │
│ 159 │ net.model.backbone.fpn.inner_blocks.2         │ Conv2dNormActivation     │  262 K │
│ 160 │ net.model.backbone.fpn.inner_blocks.2.0       │ Conv2d                   │  262 K │
│ 161 │ net.model.backbone.fpn.inner_blocks.3         │ Conv2dNormActivation     │  524 K │
│ 162 │ net.model.backbone.fpn.inner_blocks.3.0       │ Conv2d                   │  524 K │
│ 163 │ net.model.backbone.fpn.layer_blocks           │ ModuleList               │  2.4 M │
│ 164 │ net.model.backbone.fpn.layer_blocks.0         │ Conv2dNormActivation     │  590 K │
│ 165 │ net.model.backbone.fpn.layer_blocks.0.0       │ Conv2d                   │  590 K │
│ 166 │ net.model.backbone.fpn.layer_blocks.1         │ Conv2dNormActivation     │  590 K │
│ 167 │ net.model.backbone.fpn.layer_blocks.1.0       │ Conv2d                   │  590 K │
│ 168 │ net.model.backbone.fpn.layer_blocks.2         │ Conv2dNormActivation     │  590 K │
│ 169 │ net.model.backbone.fpn.layer_blocks.2.0       │ Conv2d                   │  590 K │
│ 170 │ net.model.backbone.fpn.layer_blocks.3         │ Conv2dNormActivation     │  590 K │
│ 171 │ net.model.backbone.fpn.layer_blocks.3.0       │ Conv2d                   │  590 K │
│ 172 │ net.model.backbone.fpn.extra_blocks           │ LastLevelMaxPool         │      0 │
│ 173 │ net.model.rpn                                 │ RegionProposalNetwork    │  593 K │
│ 174 │ net.model.rpn.anchor_generator                │ AnchorGenerator          │      0 │
│ 175 │ net.model.rpn.head                            │ RPNHead                  │  593 K │
│ 176 │ net.model.rpn.head.conv                       │ Sequential               │  590 K │
│ 177 │ net.model.rpn.head.conv.0                     │ Conv2dNormActivation     │  590 K │
│ 178 │ net.model.rpn.head.conv.0.0                   │ Conv2d                   │  590 K │
│ 179 │ net.model.rpn.head.conv.0.1                   │ ReLU                     │      0 │
│ 180 │ net.model.rpn.head.cls_logits                 │ Conv2d                   │    771 │
│ 181 │ net.model.rpn.head.bbox_pred                  │ Conv2d                   │  3.1 K │
│ 182 │ net.model.roi_heads                           │ RoIHeads                 │ 13.9 M │
│ 183 │ net.model.roi_heads.box_roi_pool              │ MultiScaleRoIAlign       │      0 │
│ 184 │ net.model.roi_heads.box_head                  │ TwoMLPHead               │ 13.9 M │
│ 185 │ net.model.roi_heads.box_head.fc6              │ Linear                   │ 12.8 M │
│ 186 │ net.model.roi_heads.box_head.fc7              │ Linear                   │  1.0 M │
│ 187 │ net.model.roi_heads.box_predictor             │ FastRCNNPredictor        │ 10.2 K │
│ 188 │ net.model.roi_heads.box_predictor.cls_score   │ Linear                   │  2.0 K │
│ 189 │ net.model.roi_heads.box_predictor.bbox_pred   │ Linear                   │  8.2 K │
└─────┴───────────────────────────────────────────────┴──────────────────────────┴────────┘
Trainable params: 41.1 M                                                                                                                                                                                 
Non-trainable params: 222 K                                                                                                                                                                              
Total params: 41.3 M                                                                                                                                                                                     
Total estimated model params size (MB): 165                                                                                                                                                              
At validation epoch 0
'Total loss = ' 1.6024794578552246 'Loss box = ' 0.6547712087631226 'Loss objectness = ' 0.3543730676174164 'Loss rpn box reg = ' 0.014962203800678253 'Loss classifier = ' 0.5783728957176208 
[[36m2023-04-25 12:43:18,167[0m][[34mtorch.nn.parallel.distributed[0m][[32mINFO[0m] - Reducer buckets have been rebuilt in this iteration.[0m
At validation epoch 0
'Total loss = ' 1.739322543144226 'Loss box = ' 0.7315844297409058 'Loss objectness = ' 0.401164710521698 'Loss rpn box reg = ' 0.02014869451522827 'Loss classifier = ' 0.586424708366394 
[[36m2023-04-25 12:43:18,192[0m][[34mtorch.nn.parallel.distributed[0m][[32mINFO[0m] - Reducer buckets have been rebuilt in this iteration.[0m
At validation epoch 0
'Total loss = ' 1.6705111265182495 'Loss box = ' 0.7339760065078735 'Loss objectness = ' 0.32080399990081787 'Loss rpn box reg = ' 0.016351092606782913 'Loss classifier = ' 0.5993800163269043 
[[36m2023-04-25 12:43:18,290[0m][[34mtorch.nn.parallel.distributed[0m][[32mINFO[0m] - Reducer buckets have been rebuilt in this iteration.[0m
At validation epoch 0
'Total loss = ' 1.5105417966842651 'Loss box = ' 0.6184829473495483 'Loss objectness = ' 0.29817354679107666 'Loss rpn box reg = ' 0.015284438617527485 'Loss classifier = ' 0.5786008834838867 
[[36m2023-04-25 12:43:18,290[0m][[34mtorch.nn.parallel.distributed[0m][[32mINFO[0m] - Reducer buckets have been rebuilt in this iteration.[0m
At validation epoch 0
'Total loss = ' 1.145082950592041 'Loss box = ' 0.40074586868286133 'Loss objectness = ' 0.30438458919525146 'Loss rpn box reg = ' 0.04026252403855324 'Loss classifier = ' 0.39968985319137573 
At validation epoch 1
'Total loss = ' 1.1290111541748047 'Loss box = ' 0.4769419729709625 'Loss objectness = ' 0.23036925494670868 'Loss rpn box reg = ' 0.042064037173986435 'Loss classifier = ' 0.37963587045669556 
At validation epoch 2
'Total loss = ' 1.10316002368927 'Loss box = ' 0.5000487565994263 'Loss objectness = ' 0.1887640506029129 'Loss rpn box reg = ' 0.040537647902965546 'Loss classifier = ' 0.3738095164299011 
At validation epoch 3
'Total loss = ' 1.0561965703964233 'Loss box = ' 0.5020638704299927 'Loss objectness = ' 0.15985490381717682 'Loss rpn box reg = ' 0.038901228457689285 'Loss classifier = ' 0.3553764224052429 
At validation epoch 4
'Total loss = ' 0.9881688356399536 'Loss box = ' 0.48341649770736694 'Loss objectness = ' 0.13747577369213104 'Loss rpn box reg = ' 0.03685642033815384 'Loss classifier = ' 0.33042004704475403 
At validation epoch 5
'Total loss = ' 0.9220067858695984 'Loss box = ' 0.4588952362537384 'Loss objectness = ' 0.11978500336408615 'Loss rpn box reg = ' 0.034935686737298965 'Loss classifier = ' 0.308390736579895 
At validation epoch 6
'Total loss = ' 0.8674605488777161 'Loss box = ' 0.43761858344078064 'Loss objectness = ' 0.10609044879674911 'Loss rpn box reg = ' 0.03305048868060112 'Loss classifier = ' 0.2907009422779083 
At validation epoch 7
'Total loss = ' 0.8180062174797058 'Loss box = ' 0.4164164960384369 'Loss objectness = ' 0.09562929719686508 'Loss rpn box reg = ' 0.031060056760907173 'Loss classifier = ' 0.27490028738975525 
At validation epoch 8
'Total loss = ' 0.7785982489585876 'Loss box = ' 0.3998431861400604 'Loss objectness = ' 0.0869869664311409 'Loss rpn box reg = ' 0.029269305989146233 'Loss classifier = ' 0.26249876618385315 
At validation epoch 9
'Total loss = ' 0.7441335916519165 'Loss box = ' 0.3845224976539612 'Loss objectness = ' 0.07977639883756638 'Loss rpn box reg = ' 0.028306646272540092 'Loss classifier = ' 0.2515280544757843 
At validation epoch 10
'Total loss = ' 0.716081440448761 'Loss box = ' 0.3701898753643036 'Loss objectness = ' 0.07405010610818863 'Loss rpn box reg = ' 0.027236565947532654 'Loss classifier = ' 0.24460482597351074 
At validation epoch 11
'Total loss = ' 0.6890476942062378 'Loss box = ' 0.35768285393714905 'Loss objectness = ' 0.06882919371128082 'Loss rpn box reg = ' 0.02629629150032997 'Loss classifier = ' 0.2362392544746399 
At validation epoch 12
'Total loss = ' 0.6640051007270813 'Loss box = ' 0.3457740843296051 'Loss objectness = ' 0.06444762647151947 'Loss rpn box reg = ' 0.025179050862789154 'Loss classifier = ' 0.2286042422056198 
At validation epoch 13
'Total loss = ' 0.6426069140434265 'Loss box = ' 0.33547243475914 'Loss objectness = ' 0.06082306057214737 'Loss rpn box reg = ' 0.024339716881513596 'Loss classifier = ' 0.22197166085243225 
At validation epoch 14
'Total loss = ' 0.6235815286636353 'Loss box = ' 0.32639309763908386 'Loss objectness = ' 0.05751916393637657 'Loss rpn box reg = ' 0.023510316386818886 'Loss classifier = ' 0.216158926486969 
At validation epoch 15
'Total loss = ' 0.6072909832000732 'Loss box = ' 0.3190560042858124 'Loss objectness = ' 0.05463442578911781 'Loss rpn box reg = ' 0.022734176367521286 'Loss classifier = ' 0.21086633205413818 
At validation epoch 16
'Total loss = ' 0.5924708247184753 'Loss box = ' 0.3121243119239807 'Loss objectness = ' 0.05240160599350929 'Loss rpn box reg = ' 0.022019969299435616 'Loss classifier = ' 0.20592491328716278 
At validation epoch 17
'Total loss = ' 0.5777488946914673 'Loss box = ' 0.30500948429107666 'Loss objectness = ' 0.050091877579689026 'Loss rpn box reg = ' 0.021399913355708122 'Loss classifier = ' 0.20124758780002594 
At validation epoch 18
'Total loss = ' 0.5654312372207642 'Loss box = ' 0.29886239767074585 'Loss objectness = ' 0.04808561131358147 'Loss rpn box reg = ' 0.020941313356161118 'Loss classifier = ' 0.19754189252853394 
At validation epoch 19
'Total loss = ' 0.5537075996398926 'Loss box = ' 0.29328617453575134 'Loss objectness = ' 0.04626886919140816 'Loss rpn box reg = ' 0.02040945552289486 'Loss classifier = ' 0.19374310970306396 
At validation epoch 20
'Total loss = ' 0.5441138744354248 'Loss box = ' 0.2882802486419678 'Loss objectness = ' 0.04471238702535629 'Loss rpn box reg = ' 0.019920367747545242 'Loss classifier = ' 0.191200852394104 
At validation epoch 21
'Total loss = ' 0.5337694883346558 'Loss box = ' 0.2832924425601959 'Loss objectness = ' 0.04316624999046326 'Loss rpn box reg = ' 0.01948043704032898 'Loss classifier = ' 0.18783032894134521 
At validation epoch 22
'Total loss = ' 0.5245436429977417 'Loss box = ' 0.2786911725997925 'Loss objectness = ' 0.041784875094890594 'Loss rpn box reg = ' 0.01907169818878174 'Loss classifier = ' 0.1849958896636963 
At validation epoch 23
'Total loss = ' 0.5158928632736206 'Loss box = ' 0.27450013160705566 'Loss objectness = ' 0.040672145783901215 'Loss rpn box reg = ' 0.018695849925279617 'Loss classifier = ' 0.18202471733093262 
At validation epoch 24
'Total loss = ' 0.508659839630127 'Loss box = ' 0.2713017761707306 'Loss objectness = ' 0.03946637734770775 'Loss rpn box reg = ' 0.018346043303608894 'Loss classifier = ' 0.17954561114311218 
At validation epoch 25
'Total loss = ' 0.5014241933822632 'Loss box = ' 0.2679469585418701 'Loss objectness = ' 0.03827812150120735 'Loss rpn box reg = ' 0.01805248111486435 'Loss classifier = ' 0.17714661359786987 
At validation epoch 26
'Total loss = ' 0.49569395184516907 'Loss box = ' 0.26538679003715515 'Loss objectness = ' 0.037284862250089645 'Loss rpn box reg = ' 0.01779765821993351 'Loss classifier = ' 0.1752246767282486 
At validation epoch 27
'Total loss = ' 0.49029624462127686 'Loss box = ' 0.2629707157611847 'Loss objectness = ' 0.0362999401986599 'Loss rpn box reg = ' 0.017756018787622452 'Loss classifier = ' 0.173269584774971 
At validation epoch 28
'Total loss = ' 0.4858253002166748 'Loss box = ' 0.26020392775535583 'Loss objectness = ' 0.03554725646972656 'Loss rpn box reg = ' 0.01749347150325775 'Loss classifier = ' 0.17258068919181824 
At validation epoch 29
'Total loss = ' 0.48038449883461 'Loss box = ' 0.2577197253704071 'Loss objectness = ' 0.03470565751194954 'Loss rpn box reg = ' 0.017244894057512283 'Loss classifier = ' 0.17071427404880524 
[[36m2023-04-25 12:58:14,243[0m][[34mpytorch_lightning.utilities.rank_zero[0m][[32mINFO[0m] - `Trainer.fit` stopped: `max_epochs=30` reached.[0m
Epoch 29/29 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26/26 0:00:26 • 0:00:00 0.98it/s v_num: ault validation/loss: 0.48 validation/loss_box: 0.258 validation/loss_objectness: 0.035                     
                                                                                      validation/loss_rpn_box_reg: 0.017 validation/loss_classifier: 0.171                                               
[[36m2023-04-25 12:58:14,519[0m][[34mobject_detection.training_pipeline[0m][[32mINFO[0m] - Starting testing![0m
[[36m2023-04-25 12:58:14,598[0m][[34mpytorch_lightning.utilities.rank_zero[0m][[32mINFO[0m] - You are using a CUDA device ('NVIDIA A100-SXM4-40GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision[0m
Number of training images and test images
1629 112
Dimension of the image torch.Size([3, 300, 300])
[[36m2023-04-25 12:58:14,664[0m][[34mpytorch_lightning.utilities.rank_zero[0m][[32mINFO[0m] - Restoring states from the checkpoint path at /p/project/hai_hmgu/workspace/harsha/ObjectDetection/scripts/logs/experiments/runs/default/2023-04-25_12-42-09/checkpoints/epoch_029.ckpt[0m
At validation epoch 0
'Total loss = ' 1.25054931640625 'Loss box = ' 0.4687448740005493 'Loss objectness = ' 0.3094717860221863 'Loss rpn box reg = ' 0.04877234622836113 'Loss classifier = ' 0.42356035113334656 
At validation epoch 1
'Total loss = ' 1.2264684438705444 'Loss box = ' 0.5272431373596191 'Loss objectness = ' 0.23971939086914062 'Loss rpn box reg = ' 0.04940567538142204 'Loss classifier = ' 0.41010019183158875 
At validation epoch 2
'Total loss = ' 1.180602788925171 'Loss box = ' 0.533057689666748 'Loss objectness = ' 0.1995524764060974 'Loss rpn box reg = ' 0.0485181100666523 'Loss classifier = ' 0.39947453141212463 
At validation epoch 3
'Total loss = ' 1.1209222078323364 'Loss box = ' 0.5282616019248962 'Loss objectness = ' 0.16891178488731384 'Loss rpn box reg = ' 0.045596566051244736 'Loss classifier = ' 0.37815234065055847 
At validation epoch 4
'Total loss = ' 1.0500707626342773 'Loss box = ' 0.5068365335464478 'Loss objectness = ' 0.14854618906974792 'Loss rpn box reg = ' 0.04313752055168152 'Loss classifier = ' 0.35155054926872253 
At validation epoch 5
'Total loss = ' 0.978644847869873 'Loss box = ' 0.4796854853630066 'Loss objectness = ' 0.1302768737077713 'Loss rpn box reg = ' 0.040442246943712234 'Loss classifier = ' 0.3282403349876404 
At validation epoch 6
'Total loss = ' 0.9176444411277771 'Loss box = ' 0.4558332562446594 'Loss objectness = ' 0.11598313599824905 'Loss rpn box reg = ' 0.03792344406247139 'Loss classifier = ' 0.3079046308994293 
At validation epoch 7
'Total loss = ' 0.8647127747535706 'Loss box = ' 0.4329547584056854 'Loss objectness = ' 0.10517655313014984 'Loss rpn box reg = ' 0.03551466390490532 'Loss classifier = ' 0.29106685519218445 
At validation epoch 8
'Total loss = ' 0.8206788897514343 'Loss box = ' 0.41388362646102905 'Loss objectness = ' 0.09629607945680618 'Loss rpn box reg = ' 0.03336704894900322 'Loss classifier = ' 0.27713221311569214 
At validation epoch 9
'Total loss = ' 0.7835698127746582 'Loss box = ' 0.39668846130371094 'Loss objectness = ' 0.08892296254634857 'Loss rpn box reg = ' 0.03226786479353905 'Loss classifier = ' 0.2656906545162201 
At validation epoch 10
'Total loss = ' 0.7530516982078552 'Loss box = ' 0.3813055455684662 'Loss objectness = ' 0.0828518196940422 'Loss rpn box reg = ' 0.030910132452845573 'Loss classifier = ' 0.25798436999320984 
At validation epoch 11
'Total loss = ' 0.7240029573440552 'Loss box = ' 0.36731475591659546 'Loss objectness = ' 0.07761085033416748 'Loss rpn box reg = ' 0.029668651521205902 'Loss classifier = ' 0.2494088113307953 
At validation epoch 12
'Total loss = ' 0.6979124546051025 'Loss box = ' 0.35476964712142944 'Loss objectness = ' 0.07312945276498795 'Loss rpn box reg = ' 0.02839692495763302 'Loss classifier = ' 0.24161654710769653 
At validation epoch 13
'Total loss = ' 0.6755141019821167 'Loss box = ' 0.34400349855422974 'Loss objectness = ' 0.06945212930440903 'Loss rpn box reg = ' 0.027477512136101723 'Loss classifier = ' 0.23458103835582733 
At validation epoch 14
'Total loss = ' 0.6554087400436401 'Loss box = ' 0.3344120681285858 'Loss objectness = ' 0.06596841663122177 'Loss rpn box reg = ' 0.02645976096391678 'Loss classifier = ' 0.22856858372688293 
At validation epoch 15
'Total loss = ' 0.637965738773346 'Loss box = ' 0.3262737989425659 'Loss objectness = ' 0.06324296444654465 'Loss rpn box reg = ' 0.02554289437830448 'Loss classifier = ' 0.22290614247322083 
At validation epoch 16
'Total loss = ' 0.6217612624168396 'Loss box = ' 0.31843170523643494 'Loss objectness = ' 0.060673680156469345 'Loss rpn box reg = ' 0.024686725810170174 'Loss classifier = ' 0.21796923875808716 
At validation epoch 17
'Total loss = ' 0.6061534285545349 'Loss box = ' 0.31082355976104736 'Loss objectness = ' 0.058259572833776474 'Loss rpn box reg = ' 0.02394936978816986 'Loss classifier = ' 0.21312104165554047 
At validation epoch 18
'Total loss = ' 0.5923013687133789 'Loss box = ' 0.30418989062309265 'Loss objectness = ' 0.05600009113550186 'Loss rpn box reg = ' 0.023387361317873 'Loss classifier = ' 0.20872406661510468 
At validation epoch 19
'Total loss = ' 0.5796259045600891 'Loss box = ' 0.29803338646888733 'Loss objectness = ' 0.054159872233867645 'Loss rpn box reg = ' 0.02278643101453781 'Loss classifier = ' 0.2046462595462799 
At validation epoch 20
'Total loss = ' 0.5691040754318237 'Loss box = ' 0.2926361560821533 'Loss objectness = ' 0.05232889577746391 'Loss rpn box reg = ' 0.022197019308805466 'Loss classifier = ' 0.20194202661514282 
At validation epoch 21
'Total loss = ' 0.5580013990402222 'Loss box = ' 0.2874521017074585 'Loss objectness = ' 0.05076002702116966 'Loss rpn box reg = ' 0.021669041365385056 'Loss classifier = ' 0.19812031090259552 
At validation epoch 22
'Total loss = ' 0.5482779741287231 'Loss box = ' 0.2827353775501251 'Loss objectness = ' 0.049245547503232956 'Loss rpn box reg = ' 0.02118540182709694 'Loss classifier = ' 0.19511167705059052 
At validation epoch 23
'Total loss = ' 0.538588285446167 'Loss box = ' 0.2779754102230072 'Loss objectness = ' 0.047888170927762985 'Loss rpn box reg = ' 0.020777026191353798 'Loss classifier = ' 0.19194774329662323 
At validation epoch 24
'Total loss = ' 0.5310415625572205 'Loss box = ' 0.27466529607772827 'Loss objectness = ' 0.04670731723308563 'Loss rpn box reg = ' 0.02037471905350685 'Loss classifier = ' 0.1892942637205124 
At validation epoch 25
'Total loss = ' 0.5233342051506042 'Loss box = ' 0.2711781859397888 'Loss objectness = ' 0.04543563351035118 'Loss rpn box reg = ' 0.020012808963656425 'Loss classifier = ' 0.18670763075351715 
At validation epoch 26
'Total loss = ' 0.516882598400116 'Loss box = ' 0.2682563364505768 'Loss objectness = ' 0.044435080140829086 'Loss rpn box reg = ' 0.019678836688399315 'Loss classifier = ' 0.18451236188411713 
At validation epoch 27
'Total loss = ' 0.5109098553657532 'Loss box = ' 0.26562491059303284 'Loss objectness = ' 0.04347377270460129 'Loss rpn box reg = ' 0.019619110971689224 'Loss classifier = ' 0.18219207227230072 
At validation epoch 28
'Total loss = ' 0.5061124563217163 'Loss box = ' 0.26260262727737427 'Loss objectness = ' 0.04272850975394249 'Loss rpn box reg = ' 0.019333599135279655 'Loss classifier = ' 0.18144778907299042 
At validation epoch 29
'Total loss = ' 0.49972862005233765 'Loss box = ' 0.2596741318702698 'Loss objectness = ' 0.04176876321434975 'Loss rpn box reg = ' 0.01902315393090248 'Loss classifier = ' 0.17926262319087982 
Number of training images and test images
1629 112
Dimension of the image torch.Size([3, 300, 300])
[[36m2023-04-25 12:58:16,008[0m][[34mpytorch_lightning.accelerators.cuda[0m][[32mINFO[0m] - LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3     ][0m
At validation epoch 0
'Total loss = ' 1.2136163711547852 'Loss box = ' 0.45599231123924255 'Loss objectness = ' 0.2882334589958191 'Loss rpn box reg = ' 0.04278935119509697 'Loss classifier = ' 0.42660126090049744 
At validation epoch 1
'Total loss = ' 1.199017882347107 'Loss box = ' 0.5226575136184692 'Loss objectness = ' 0.2270282357931137 'Loss rpn box reg = ' 0.04414590820670128 'Loss classifier = ' 0.40518638491630554 
At validation epoch 2
'Total loss = ' 1.1635427474975586 'Loss box = ' 0.534593403339386 'Loss objectness = ' 0.19004584848880768 'Loss rpn box reg = ' 0.043185267597436905 'Loss classifier = ' 0.39571842551231384 
At validation epoch 3
'Total loss = ' 1.105628252029419 'Loss box = ' 0.5308173298835754 'Loss objectness = ' 0.1599261462688446 'Loss rpn box reg = ' 0.04123112931847572 'Loss classifier = ' 0.37365368008613586 
At validation epoch 4
'Total loss = ' 1.0304638147354126 'Loss box = ' 0.5048604011535645 'Loss objectness = ' 0.13910984992980957 'Loss rpn box reg = ' 0.03940823674201965 'Loss classifier = ' 0.34708553552627563 
At validation epoch 5
'Total loss = ' 0.9587898850440979 'Loss box = ' 0.47576218843460083 'Loss objectness = ' 0.12157494574785233 'Loss rpn box reg = ' 0.03706405311822891 'Loss classifier = ' 0.3243887722492218 
At validation epoch 6
'Total loss = ' 0.8995043635368347 'Loss box = ' 0.45044368505477905 'Loss objectness = ' 0.10825091600418091 'Loss rpn box reg = ' 0.03489447385072708 'Loss classifier = ' 0.3059154450893402 
At validation epoch 7
'Total loss = ' 0.847874104976654 'Loss box = ' 0.4267013370990753 'Loss objectness = ' 0.09740537405014038 'Loss rpn box reg = ' 0.032736871391534805 'Loss classifier = ' 0.2910306453704834 
At validation epoch 8
'Total loss = ' 0.8047844171524048 'Loss box = ' 0.4072249233722687 'Loss objectness = ' 0.08884648233652115 'Loss rpn box reg = ' 0.030712680891156197 'Loss classifier = ' 0.27800044417381287 
At validation epoch 9
'Total loss = ' 0.7685655355453491 'Loss box = ' 0.3902677893638611 'Loss objectness = ' 0.08189107477664948 'Loss rpn box reg = ' 0.029783252626657486 'Loss classifier = ' 0.26662352681159973 
At validation epoch 10
'Total loss = ' 0.7378115653991699 'Loss box = ' 0.3734862804412842 'Loss objectness = ' 0.07592210173606873 'Loss rpn box reg = ' 0.028435029089450836 'Loss classifier = ' 0.25996825098991394 
At validation epoch 11
'Total loss = ' 0.7086921334266663 'Loss box = ' 0.3590605854988098 'Loss objectness = ' 0.0707557201385498 'Loss rpn box reg = ' 0.027315450832247734 'Loss classifier = ' 0.2515605092048645 
At validation epoch 12
'Total loss = ' 0.6821863651275635 'Loss box = ' 0.3463819921016693 'Loss objectness = ' 0.06634369492530823 'Loss rpn box reg = ' 0.02612799033522606 'Loss classifier = ' 0.24333275854587555 
At validation epoch 13
'Total loss = ' 0.6587240099906921 'Loss box = ' 0.33466652035713196 'Loss objectness = ' 0.06263245642185211 'Loss rpn box reg = ' 0.025266079232096672 'Loss classifier = ' 0.236159086227417 
At validation epoch 14
'Total loss = ' 0.6383992433547974 'Loss box = ' 0.3247778117656708 'Loss objectness = ' 0.05938981473445892 'Loss rpn box reg = ' 0.02428395114839077 'Loss classifier = ' 0.2299477458000183 
At validation epoch 15
'Total loss = ' 0.6201984286308289 'Loss box = ' 0.3159429132938385 'Loss objectness = ' 0.056601520627737045 'Loss rpn box reg = ' 0.023363111540675163 'Loss classifier = ' 0.22429095208644867 
At validation epoch 16
'Total loss = ' 0.6033972501754761 'Loss box = ' 0.30776476860046387 'Loss objectness = ' 0.05416715145111084 'Loss rpn box reg = ' 0.02252660132944584 'Loss classifier = ' 0.21893887221813202 
At validation epoch 17
'Total loss = ' 0.5875075459480286 'Loss box = ' 0.2997807562351227 'Loss objectness = ' 0.05167931318283081 'Loss rpn box reg = ' 0.021808410063385963 'Loss classifier = ' 0.2142392098903656 
At validation epoch 18
'Total loss = ' 0.5730406045913696 'Loss box = ' 0.292745977640152 'Loss objectness = ' 0.04945999011397362 'Loss rpn box reg = ' 0.021229293197393417 'Loss classifier = ' 0.2096053957939148 
At validation epoch 19
'Total loss = ' 0.5601839423179626 'Loss box = ' 0.28661099076271057 'Loss objectness = ' 0.047604672610759735 'Loss rpn box reg = ' 0.0206318199634552 'Loss classifier = ' 0.2053365409374237 
At validation epoch 20
'Total loss = ' 0.5498673915863037 'Loss box = ' 0.28116029500961304 'Loss objectness = ' 0.0458478145301342 'Loss rpn box reg = ' 0.0200722124427557 'Loss classifier = ' 0.2027871310710907 
At validation epoch 21
'Total loss = ' 0.5387018322944641 'Loss box = ' 0.275918573141098 'Loss objectness = ' 0.044200971722602844 'Loss rpn box reg = ' 0.019554084166884422 'Loss classifier = ' 0.19902831315994263 
At validation epoch 22
'Total loss = ' 0.5287537574768066 'Loss box = ' 0.2710025906562805 'Loss objectness = ' 0.04277433082461357 'Loss rpn box reg = ' 0.019092580303549767 'Loss classifier = ' 0.1958843469619751 
At validation epoch 23
'Total loss = ' 0.5194723606109619 'Loss box = ' 0.26645180583000183 'Loss objectness = ' 0.04156958684325218 'Loss rpn box reg = ' 0.018670791760087013 'Loss classifier = ' 0.1927803009748459 
At validation epoch 24
'Total loss = ' 0.5116104483604431 'Loss box = ' 0.26291581988334656 'Loss objectness = ' 0.04036740958690643 'Loss rpn box reg = ' 0.01827816478908062 'Loss classifier = ' 0.19004908204078674 
At validation epoch 25
'Total loss = ' 0.5039492845535278 'Loss box = ' 0.2594582438468933 'Loss objectness = ' 0.03926853463053703 'Loss rpn box reg = ' 0.01794503629207611 'Loss classifier = ' 0.18727754056453705 
At validation epoch 26
'Total loss = ' 0.4972676634788513 'Loss box = ' 0.25638505816459656 'Loss objectness = ' 0.038121677935123444 'Loss rpn box reg = ' 0.017622778192162514 'Loss classifier = ' 0.18513818085193634 
At validation epoch 27
'Total loss = ' 0.4915177524089813 'Loss box = ' 0.2539174556732178 'Loss objectness = ' 0.03719090297818184 'Loss rpn box reg = ' 0.01762511022388935 'Loss classifier = ' 0.18278434872627258 
At validation epoch 28
'Total loss = ' 0.48602765798568726 'Loss box = ' 0.2506510019302368 'Loss objectness = ' 0.03648975491523743 'Loss rpn box reg = ' 0.017322946339845657 'Loss classifier = ' 0.18156401813030243 
At validation epoch 29
'Total loss = ' 0.4799070656299591 'Loss box = ' 0.24755960702896118 'Loss objectness = ' 0.03560950979590416 'Loss rpn box reg = ' 0.017007725313305855 'Loss classifier = ' 0.17973026633262634 
Number of training images and test images
1629 112
Dimension of the image torch.Size([3, 300, 300])
[[36m2023-04-25 12:58:16,018[0m][[34mpytorch_lightning.accelerators.cuda[0m][[32mINFO[0m] - LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,2,3     ][0m
At validation epoch 0
'Total loss = ' 1.0820679664611816 'Loss box = ' 0.383861243724823 'Loss objectness = ' 0.2686040699481964 'Loss rpn box reg = ' 0.03549928590655327 'Loss classifier = ' 0.39410340785980225 
At validation epoch 1
'Total loss = ' 1.0595148801803589 'Loss box = ' 0.4434083104133606 'Loss objectness = ' 0.20589891076087952 'Loss rpn box reg = ' 0.03712116554379463 'Loss classifier = ' 0.37308645248413086 
At validation epoch 2
'Total loss = ' 1.0355968475341797 'Loss box = ' 0.46363499760627747 'Loss objectness = ' 0.1712159514427185 'Loss rpn box reg = ' 0.0360468253493309 'Loss classifier = ' 0.3646991550922394 
At validation epoch 3
'Total loss = ' 0.9950857162475586 'Loss box = ' 0.4685157239437103 'Loss objectness = ' 0.14546681940555573 'Loss rpn box reg = ' 0.03398890420794487 'Loss classifier = ' 0.34711429476737976 
At validation epoch 4
'Total loss = ' 0.9275913238525391 'Loss box = ' 0.44913631677627563 'Loss objectness = ' 0.12533850967884064 'Loss rpn box reg = ' 0.032029181718826294 'Loss classifier = ' 0.32108739018440247 
At validation epoch 5
'Total loss = ' 0.8612616062164307 'Loss box = ' 0.42440760135650635 'Loss objectness = ' 0.10942885279655457 'Loss rpn box reg = ' 0.03007080778479576 'Loss classifier = ' 0.29735442996025085 
At validation epoch 6
'Total loss = ' 0.8069612979888916 'Loss box = ' 0.40349456667900085 'Loss objectness = ' 0.09682163596153259 'Loss rpn box reg = ' 0.028304606676101685 'Loss classifier = ' 0.27834054827690125 
At validation epoch 7
'Total loss = ' 0.7600961327552795 'Loss box = ' 0.38398978114128113 'Loss objectness = ' 0.08661190420389175 'Loss rpn box reg = ' 0.026485154405236244 'Loss classifier = ' 0.26300930976867676 
At validation epoch 8
'Total loss = ' 0.7216237187385559 'Loss box = ' 0.36766090989112854 'Loss objectness = ' 0.07848535478115082 'Loss rpn box reg = ' 0.024904565885663033 'Loss classifier = ' 0.25057294964790344 
At validation epoch 9
'Total loss = ' 0.6902857422828674 'Loss box = ' 0.35400229692459106 'Loss objectness = ' 0.0721948966383934 'Loss rpn box reg = ' 0.024101320654153824 'Loss classifier = ' 0.23998726904392242 
At validation epoch 10
'Total loss = ' 0.6639198064804077 'Loss box = ' 0.3406195342540741 'Loss objectness = ' 0.06718946248292923 'Loss rpn box reg = ' 0.02317764237523079 'Loss classifier = ' 0.23293320834636688 
At validation epoch 11
'Total loss = ' 0.638160765171051 'Loss box = ' 0.328813761472702 'Loss objectness = ' 0.06273495405912399 'Loss rpn box reg = ' 0.022283930331468582 'Loss classifier = ' 0.2243281453847885 
At validation epoch 12
'Total loss = ' 0.6147364974021912 'Loss box = ' 0.3180963099002838 'Loss objectness = ' 0.05868927761912346 'Loss rpn box reg = ' 0.02128475531935692 'Loss classifier = ' 0.21666622161865234 
At validation epoch 13
'Total loss = ' 0.5948094725608826 'Loss box = ' 0.30898019671440125 'Loss objectness = ' 0.05542030930519104 'Loss rpn box reg = ' 0.02055571787059307 'Loss classifier = ' 0.2098533660173416 
At validation epoch 14
'Total loss = ' 0.5766851305961609 'Loss box = ' 0.30079901218414307 'Loss objectness = ' 0.05222020298242569 'Loss rpn box reg = ' 0.01977519877254963 'Loss classifier = ' 0.20389072597026825 
At validation epoch 15
'Total loss = ' 0.56102055311203 'Loss box = ' 0.2939280867576599 'Loss objectness = ' 0.04964505508542061 'Loss rpn box reg = ' 0.019041012972593307 'Loss classifier = ' 0.1984064280986786 
At validation epoch 16
'Total loss = ' 0.5466431975364685 'Loss box = ' 0.2875726521015167 'Loss objectness = ' 0.04727114737033844 'Loss rpn box reg = ' 0.01839783601462841 'Loss classifier = ' 0.19340157508850098 
At validation epoch 17
'Total loss = ' 0.5326073169708252 'Loss box = ' 0.2807929217815399 'Loss objectness = ' 0.04509114846587181 'Loss rpn box reg = ' 0.017831681296229362 'Loss classifier = ' 0.18889158964157104 
At validation epoch 18
'Total loss = ' 0.5208756327629089 'Loss box = ' 0.2752191126346588 'Loss objectness = ' 0.0431322306394577 'Loss rpn box reg = ' 0.017422860488295555 'Loss classifier = ' 0.1851014494895935 
At validation epoch 19
'Total loss = ' 0.5096410512924194 'Loss box = ' 0.2698866128921509 'Loss objectness = ' 0.04132368043065071 'Loss rpn box reg = ' 0.01693585328757763 'Loss classifier = ' 0.18149493634700775 
At validation epoch 20
'Total loss = ' 0.5005238056182861 'Loss box = ' 0.2653186619281769 'Loss objectness = ' 0.03979332745075226 'Loss rpn box reg = ' 0.016502872109413147 'Loss classifier = ' 0.17890891432762146 
At validation epoch 21
'Total loss = ' 0.49036452174186707 'Loss box = ' 0.26065123081207275 'Loss objectness = ' 0.03825712203979492 'Loss rpn box reg = ' 0.01610507443547249 'Loss classifier = ' 0.17535105347633362 
At validation epoch 22
'Total loss = ' 0.48181718587875366 'Loss box = ' 0.2566402554512024 'Loss objectness = ' 0.03686194866895676 'Loss rpn box reg = ' 0.01571834646165371 'Loss classifier = ' 0.17259660363197327 
At validation epoch 23
'Total loss = ' 0.4732760190963745 'Loss box = ' 0.2527264952659607 'Loss objectness = ' 0.035628728568553925 'Loss rpn box reg = ' 0.015394018031656742 'Loss classifier = ' 0.16952675580978394 
At validation epoch 24
'Total loss = ' 0.46624642610549927 'Loss box = ' 0.2497757077217102 'Loss objectness = ' 0.034557364881038666 'Loss rpn box reg = ' 0.015081778168678284 'Loss classifier = ' 0.16683150827884674 
At validation epoch 25
'Total loss = ' 0.4595082104206085 'Loss box = ' 0.24687567353248596 'Loss objectness = ' 0.03350163251161575 'Loss rpn box reg = ' 0.014815897680819035 'Loss classifier = ' 0.16431495547294617 
At validation epoch 26
'Total loss = ' 0.4538595676422119 'Loss box = ' 0.24454504251480103 'Loss objectness = ' 0.03246384114027023 'Loss rpn box reg = ' 0.014560667797923088 'Loss classifier = ' 0.16228994727134705 
At validation epoch 27
'Total loss = ' 0.448376327753067 'Loss box = ' 0.242182657122612 'Loss objectness = ' 0.03154223784804344 'Loss rpn box reg = ' 0.01453406736254692 'Loss classifier = ' 0.16011731326580048 
At validation epoch 28
'Total loss = ' 0.44422048330307007 'Loss box = ' 0.23971572518348694 'Loss objectness = ' 0.03081362508237362 'Loss rpn box reg = ' 0.014310824684798717 'Loss classifier = ' 0.15938027203083038 
At validation epoch 29
'Total loss = ' 0.4385770261287689 'Loss box = ' 0.23717692494392395 'Loss objectness = ' 0.030041314661502838 'Loss rpn box reg = ' 0.014076138846576214 'Loss classifier = ' 0.15728260576725006 
Number of training images and test images
1629 112
Dimension of the image torch.Size([3, 300, 300])
[[36m2023-04-25 12:58:16,024[0m][[34mpytorch_lightning.accelerators.cuda[0m][[32mINFO[0m] - LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,2,3     ][0m
[[36m2023-04-25 12:58:16,037[0m][[34mpytorch_lightning.accelerators.cuda[0m][[32mINFO[0m] - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3     ][0m
[[36m2023-04-25 12:58:16,100[0m][[34mpytorch_lightning.utilities.rank_zero[0m][[32mINFO[0m] - Loaded model weights from the checkpoint at /p/project/hai_hmgu/workspace/harsha/ObjectDetection/scripts/logs/experiments/runs/default/2023-04-25_12-42-09/checkpoints/epoch_029.ckpt[0m
P-R curve values [[0.44378698 0.52214452 0.56708861 0.60215054 0.65588235 0.69375
  0.7147541  0.74216028 0.7761194  0.82683983        nan]
 [0.97402597 0.96969697 0.96969697 0.96969697 0.96536797 0.96103896
  0.94372294 0.92207792 0.9004329  0.82683983 0.        ]]
P-R curve values [[0.42477876 0.49382716 0.55427252 0.5975     0.62532982 0.66478873
  0.69512195 0.74662162 0.78181818 0.83467742        nan]
 [0.9486166  0.9486166  0.9486166  0.94466403 0.93675889 0.93280632
  0.90118577 0.87351779 0.84980237 0.81818182 0.        ]]
Testing ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 0:00:00 • 0:00:00 1.31it/s  
[[36m2023-04-25 12:58:26,333[0m][[34mobject_detection.training_pipeline[0m][[32mINFO[0m] - Finalizing![0m
[[36m2023-04-25 12:58:26,334[0m][[34mobject_detection.training_pipeline[0m][[32mINFO[0m] - Best model ckpt at /p/project/hai_hmgu/workspace/harsha/ObjectDetection/scripts/logs/experiments/runs/default/2023-04-25_12-42-09/checkpoints/epoch_029.ckpt[0m
P-R curve values [[0.45655877 0.53187251 0.57826087 0.60779817 0.64864865 0.68848168
  0.71428571 0.75443787 0.77993528 0.8381295         nan]
 [0.94699647 0.9434629  0.93992933 0.93639576 0.93286219 0.92932862
  0.91872792 0.90106007 0.85159011 0.82332155 0.        ]]
P-R curve values [[0.45344828 0.524      0.57906459 0.61961722 0.64411028 0.6640625
  0.70054945 0.72126437 0.75076923 0.8               nan]
 [0.97407407 0.97037037 0.96296296 0.95925926 0.95185185 0.94444444
  0.94444444 0.92962963 0.9037037  0.84444444 0.        ]]
