_target_: object_detection.datamodules.frcnn_datamodule.frcnn_datamodule

# data_dir is specified in config.yaml
train_data_dir: ${data_dir}/orgaquant/train 
val_data_dir: ${data_dir}/orgaquant/val 
test_data_dir: ${data_dir}/orgaquant/test

train_labels_file: ${data_dir}/orgaquant/train_labels.csv 
val_labels_file: ${data_dir}/orgaquant/val_labels.csv 
test_labels_file: ${data_dir}/orgaquant/test_labels.csv 

batch_size: 16
num_workers: 0
pin_memory: False
aug_flag: 'Y'
